name: flutter_tech_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  badges: ^2.0.3
  chopper: ^4.0.6
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  logging: ^1.0.2
  lottie: ^1.3.0
  responsive_sizer: ^3.0.8
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  chopper_generator: ^4.0.6
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  http: ^0.13.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.1
  lint: ^1.8.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/json/
