name: flutter_tech_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.0.1
  auto_route: ^4.2.1
  chopper: ^4.0.6
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  freezed_annotation: ^2.0.3
  http: 0.13.4
  json_annotation: ^4.6.0
  logging: ^1.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  chopper_generator: ^4.0.6
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  lint: ^1.8.2

flutter:
  uses-material-design: true
