name: flutter_tech_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  chopper: ^4.0.6
  connectivity_plus: ^2.3.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  http: 0.13.4
  logging: ^1.0.2

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11
  chopper_generator: ^4.0.6
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  lint: ^1.8.2

flutter:
  uses-material-design: true
